AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'Rakefile'
  NewCops: enable
Layout/LineLength:
  Max: 100
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe']
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 20
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Description: 'Prefer `transform_keys` over `each_with_object` and `map`.'
  Enabled: true
Style/HashTransformValues:
  Description: 'Prefer `transform_values` over `each_with_object` and `map`.'
  Enabled: true
